### ISSUE TITLE
Update 1.16.4 -> I need you as a Developer - continue MinecraftMovies Plugin!

### ISSUE THREAD

**Issue by JaHollTV** [0Adiber/MinecraftMovies#1]
Hey there,
hope its okay i contact you via an issue.

So, my Name is Jakob and i am the owner of a German 1.16.4 Minecraft Roleplay Server.
For Roleplay watching Videos / Movies would be very awesome. I saw you Plugin and its great and brilliant!

So i want to ask, if you have time and motivation to update your Plugin to 1.16.4.
If you introduce me into your Plugin maybe i can also help :)

I testet it on  Spigot-1.16.2 Server, but it didn't work correctly(nothing happend by run "/start CID FOLDER"). 

On my Roleplay Server i can provide up to 40 GB Ram, so if your plugins need Ram its no Problem :)

Would appreciate if we could get in contact. 
I have a Discord Server(http://dc.jaholl.de/) you can contact me there: JaHoll#5429

**Comment by 0Adiber** [comment]
@JaHollYT 
I'm sorry to tell you this, but that's simply not possible. As to why, can be seen in the [Performance](https://github.com/0Adiber/MinecraftMovies/#performance) section of the README. Storing the video in a more compressed format, or real-time rendering aren't the problem here... The real deal is the internet connection one would need. Even if you were to downscale the image to 480p (resulting in a smaller canvas), and only showing 1 image per second requires ~400KB/s per user to view it "smoothly". 
For your server, I would suggest you to use appropriate Mods. After all, this was more of a **Proof of Concept**, as stated in the README's introduction. 
The only possibility to use this on a real server, is to use a 128*128 video (=one item frame) with 30 fps, resulting in 500KB/s Internet usage per user.
